// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: testproto/test.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The request message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UnaryReq) Reset() {
	*x = UnaryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryReq) ProtoMessage() {}

func (x *UnaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryReq.ProtoReflect.Descriptor instead.
func (*UnaryReq) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UnaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The response message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UnaryResp) Reset() {
	*x = UnaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryResp) ProtoMessage() {}

func (x *UnaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryResp.ProtoReflect.Descriptor instead.
func (*UnaryResp) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ServerStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The request message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ServerStreamReq) Reset() {
	*x = ServerStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamReq) ProtoMessage() {}

func (x *ServerStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamReq.ProtoReflect.Descriptor instead.
func (*ServerStreamReq) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{2}
}

func (x *ServerStreamReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ServerStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The response message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ServerStreamResp) Reset() {
	*x = ServerStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamResp) ProtoMessage() {}

func (x *ServerStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamResp.ProtoReflect.Descriptor instead.
func (*ServerStreamResp) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{3}
}

func (x *ServerStreamResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClientStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The request message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ClientStreamReq) Reset() {
	*x = ClientStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamReq) ProtoMessage() {}

func (x *ClientStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamReq.ProtoReflect.Descriptor instead.
func (*ClientStreamReq) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{4}
}

func (x *ClientStreamReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClientStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The response message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ClientStreamResp) Reset() {
	*x = ClientStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResp) ProtoMessage() {}

func (x *ClientStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResp.ProtoReflect.Descriptor instead.
func (*ClientStreamResp) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{5}
}

func (x *ClientStreamResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BiDiStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The request message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BiDiStreamReq) Reset() {
	*x = BiDiStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiDiStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiDiStreamReq) ProtoMessage() {}

func (x *BiDiStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiDiStreamReq.ProtoReflect.Descriptor instead.
func (*BiDiStreamReq) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{6}
}

func (x *BiDiStreamReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BiDiStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The response message.
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BiDiStreamResp) Reset() {
	*x = BiDiStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testproto_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiDiStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiDiStreamResp) ProtoMessage() {}

func (x *BiDiStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiDiStreamResp.ProtoReflect.Descriptor instead.
func (*BiDiStreamResp) Descriptor() ([]byte, []int) {
	return file_testproto_test_proto_rawDescGZIP(), []int{7}
}

func (x *BiDiStreamResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_testproto_test_proto protoreflect.FileDescriptor

var file_testproto_test_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1c, 0x0a, 0x08, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x1d, 0x0a, 0x09, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23,
	0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x24, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x24,
	0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x0d, 0x42, 0x69, 0x44, 0x69, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x0e, 0x42, 0x69, 0x44, 0x69, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x9f, 0x02, 0x0a, 0x04,
	0x54, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x13, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x47, 0x0a, 0x0a, 0x42, 0x69, 0x44, 0x69, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x18, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x69, 0x44, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x44, 0x69, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x68, 0x73,
	0x70, 0x68, 0x69, 0x6e, 0x78, 0x2f, 0x6e, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testproto_test_proto_rawDescOnce sync.Once
	file_testproto_test_proto_rawDescData = file_testproto_test_proto_rawDesc
)

func file_testproto_test_proto_rawDescGZIP() []byte {
	file_testproto_test_proto_rawDescOnce.Do(func() {
		file_testproto_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_testproto_test_proto_rawDescData)
	})
	return file_testproto_test_proto_rawDescData
}

var file_testproto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_testproto_test_proto_goTypes = []interface{}{
	(*UnaryReq)(nil),         // 0: testproto.UnaryReq
	(*UnaryResp)(nil),        // 1: testproto.UnaryResp
	(*ServerStreamReq)(nil),  // 2: testproto.ServerStreamReq
	(*ServerStreamResp)(nil), // 3: testproto.ServerStreamResp
	(*ClientStreamReq)(nil),  // 4: testproto.ClientStreamReq
	(*ClientStreamResp)(nil), // 5: testproto.ClientStreamResp
	(*BiDiStreamReq)(nil),    // 6: testproto.BiDiStreamReq
	(*BiDiStreamResp)(nil),   // 7: testproto.BiDiStreamResp
}
var file_testproto_test_proto_depIdxs = []int32{
	0, // 0: testproto.Test.Unary:input_type -> testproto.UnaryReq
	2, // 1: testproto.Test.ServerStream:input_type -> testproto.ServerStreamReq
	4, // 2: testproto.Test.ClientStream:input_type -> testproto.ClientStreamReq
	6, // 3: testproto.Test.BiDiStream:input_type -> testproto.BiDiStreamReq
	1, // 4: testproto.Test.Unary:output_type -> testproto.UnaryResp
	3, // 5: testproto.Test.ServerStream:output_type -> testproto.ServerStreamResp
	5, // 6: testproto.Test.ClientStream:output_type -> testproto.ClientStreamResp
	7, // 7: testproto.Test.BiDiStream:output_type -> testproto.BiDiStreamResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testproto_test_proto_init() }
func file_testproto_test_proto_init() {
	if File_testproto_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testproto_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testproto_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testproto_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testproto_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testproto_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testproto_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testproto_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiDiStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testproto_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiDiStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testproto_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testproto_test_proto_goTypes,
		DependencyIndexes: file_testproto_test_proto_depIdxs,
		MessageInfos:      file_testproto_test_proto_msgTypes,
	}.Build()
	File_testproto_test_proto = out.File
	file_testproto_test_proto_rawDesc = nil
	file_testproto_test_proto_goTypes = nil
	file_testproto_test_proto_depIdxs = nil
}
